SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `general_claim_types`
ADD COLUMN `has_gst` TINYINT(1) NULL DEFAULT 1 COMMENT '' AFTER `unit`;

DROP TABLE IF EXISTS `user_salaries` ;

DROP TABLE IF EXISTS `salary_items` ;

DROP TABLE IF EXISTS `salaries` ;

DROP TABLE IF EXISTS `deductions` ;

DROP TABLE IF EXISTS `benefits` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
