 @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `general_claims` 
ADD COLUMN `archived_at` TIMESTAMP NULL DEFAULT NULL COMMENT '' AFTER `updated_at`;

ALTER TABLE `leaves` 
ADD COLUMN `archived_at` TIMESTAMP NULL DEFAULT NULL COMMENT '' AFTER `updated_at`;

ALTER TABLE `medical_claims` 
ADD COLUMN `archived_at` TIMESTAMP NULL DEFAULT NULL COMMENT '' AFTER `updated_at`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
