SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `shares`
ADD COLUMN `user_unit_id` INT(11) NULL DEFAULT NULL COMMENT '' AFTER `id`,
ADD INDEX `fk_shares_user_units1_idx` (`user_unit_id` ASC)  COMMENT '';

ALTER TABLE `shares`
ADD CONSTRAINT `fk_shares_user_units1`
  FOREIGN KEY (`user_unit_id`)
  REFERENCES `user_units` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
