SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `todo_subtasks` 
DROP FOREIGN KEY `fk_task_subtasks_todos1`;

ALTER TABLE `todo_subtasks` 
CHANGE COLUMN `todos_id` `todo_id` INT(10) UNSIGNED NOT NULL ;

ALTER TABLE `todo_subtasks` 
ADD CONSTRAINT `fk_task_subtasks_todos1`
  FOREIGN KEY (`todo_id`)
  REFERENCES `todos` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
