SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `general_claims` 
ADD COLUMN `is_paid` TINYINT(1) NULL DEFAULT 0 COMMENT '' AFTER `upload_hash`;

ALTER TABLE `medical_claims` 
ADD COLUMN `is_paid` TINYINT(1) NULL DEFAULT 0 COMMENT '' AFTER `upload_hash`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
