SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `payroll_items` 
CHANGE COLUMN `amount` `amount` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '' ;

ALTER TABLE `cloudhrd_app`.`payroll_user` 
CHANGE COLUMN `total` `total` DECIMAL(15,2) NULL DEFAULT 0.00 COMMENT '' AFTER `payroll_id`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
