SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

ALTER TABLE `user_profiles` 
ADD COLUMN `bank_name` VARCHAR(128) NULL DEFAULT NULL COMMENT '' AFTER `user_field_09`,
ADD COLUMN `bank_account` VARCHAR(128) NULL DEFAULT NULL COMMENT '' AFTER `bank_name`,
ADD COLUMN `kwsp_account` VARCHAR(128) NULL DEFAULT NULL COMMENT '' AFTER `bank_account`,
ADD COLUMN `kwsp_contribution` DECIMAL(4,1) NULL DEFAULT 8.0 COMMENT '' AFTER `kwsp_account`,
ADD COLUMN `lhdn_account` VARCHAR(128) NULL DEFAULT NULL COMMENT '' AFTER `kwsp_contribution`,
ADD COLUMN `pcb_contribution` DECIMAL(8,2) NULL DEFAULT 0.00 COMMENT '' AFTER `lhdn_account`,
ADD COLUMN `socso_account` VARCHAR(128) NULL DEFAULT NULL COMMENT '' AFTER `pcb_contribution`,
ADD COLUMN `socso_contribution` DECIMAL(6,2) NULL DEFAULT 66.40 COMMENT '' AFTER `socso_account`,
ADD COLUMN `salary` DECIMAL(12,2) NULL DEFAULT 0.00 COMMENT '' AFTER `socso_contribution`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
